name: HologramAPI
version: "${git.commit.id.abbrev}"
main: gg.manny.hologram.HologramPlugin
author: Manny
softdepend: [ProtocolSupport]
commands:
  hologram:
    usage: /hologram
    description: Manage holograms
    aliases: [holo]